# -*- coding: utf-8 -*-
"""HandsonDemo2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1R7M-DrO_-RtSP4yTNYSCN_ioyIVAzntG
"""

!apt-get install openjdk-8-jdk-headless -qq > /dev/null
!wget https://downloads.apache.org/spark/spark-3.1.3/spark-3.1.3-bin-hadoop2.7.tgz
!tar -xvf spark-3.1.3-bin-hadoop2.7.tgz
!pip install -q findspark

import os
os.environ["JAVA_HOME"] = "/usr/lib/jvm/java-8-openjdk-amd64"
os.environ["SPARK_HOME"] = "/content/spark-3.1.3-bin-hadoop2.7.tgz"

import findspark
findspark.init("spark-3.1.3-bin-hadoop2.7")# Spark Home
from pyspark.sql import SparkSession
spark = SparkSession.builder.master("local[*]").getOrCreate()

from google.colab import files
files.upload()

df = spark.read.format("csv").option("header", "true").option("mode", 'failfast').load("pseudo_facebook.csv")

df.createOrReplaceTempView("fb")

spark.sql("select * from fb").show(3)

spark.sql("select count(*) from fb").show()

spark.sql("select avg(age), gender from fb group by gender").show()

spark.sql("select avg(age) from fb").show()

x_p = spark.sql("select avg(age) from fb").collect()

x = spark.sql("select avg(age) from fb").collect()[0][0]
print(x + 3)

spark.sql("select avg(likes_received) as avg_like, gender from fb group by gender order by avg_like").show()

spark.sql("select avg(friend_count) from fb where age>=13 AND age <= 35").show()

spark.sql("select avg(mobile_likes) as avglikes, avg(www_likes) from fb where age>=13 AND age <= 35").show()

df.groupby("age").avg("likes").orderBy("age", ascending = False).show()

